---
platform: linux

image_resource:
  type: docker-image
  source: { repository: hub.global.cloud.sap/monsoon/nodebuild, tag: '8.12'}

inputs:
- name: iris.git
  path: /home/app/webapp/iris

run:
  path: /bin/bash
  args:
    - -c
    - |
      env  
