export const CLEAR_USER_PROFILE           = 'auth/CLEAR_USER_PROFILE'
export const REQUEST_LOG_ON               = 'auth/REQUEST_LOG_ON'
export const REQUEST_LOG_ON_FAILURE       = 'auth/REQUEST_LOG_ON_FALIURE'
export const REQUEST_USER_PROFILE         = 'auth/REQUEST_USER_PROFILE'
export const REQUEST_USER_PROFILE_FAILURE = 'auth/REQUEST_USER_PROFILE_FAILURE'
export const RECEIVE_USER_PROFILE         = 'auth/RECEIVE_USER_PROFILE'
